#!/usr/bin/env python
"""
Generate a Cursor .mdc rule file from canonical governance docs.

Writes:
- .cursor/rules/repo-governance.mdc
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def main() -> int:
    # Keep Cursor rule concise. Cursor injects rules into context; avoid huge payloads.
    body = "\n".join(
        [
            "## Repo governance (canonical)",
            "",
            "Canonical instructions live in `AGENTS.md` and `docs/agents/`.",
            "",
            "### Non-negotiables",
            "- Edit canonical sources (AGENTS.md, docs/agents/**, .agents/skills/**).",
            "- Do not hand-edit shim dirs (.claude/, .gemini/, .agent/, .cursor/).",
            "- After governance/skill changes: run `python scripts/agents/sync_shims.py`.",
            "- Validate before PR: `python ci/validate_agent_assets.py`.",
            "",
            "### Canonical files",
            "- `AGENTS.md`",
            "- `docs/agents/GOVERNANCE.md`",
            "",
        ]
    )

    rule_text = "\n".join(
        [
            "---",
            "description: Repo-wide governance for AI agents (canonical in AGENTS.md).",
            "alwaysApply: true",
            "globs:",
            '  - "**/*"',
            "---",
            "",
            "> AUTO-GENERATED by `scripts/agents/generate_cursor_rule.py`.",
            "",
            body,
        ]
    )

    out = REPO_ROOT / ".cursor" / "rules" / "repo-governance.mdc"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rule_text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
