#!/usr/bin/env python3
"""
Sync tool-specific agent governance shims from canonical sources.

Canonical sources:
- AGENTS.md
- docs/agents/**
- .agents/skills/**

Shims generated/maintained:
- .claude/CLAUDE.md
- .claude/skills/  (mirror of .agents/skills)
- .gemini/GEMINI.md
- .gemini/skills/  (mirror of .agents/skills)
- .gemini/knowledge/ (mirror of knowledge/)
- .agent/skills/   (mirror of .agents/skills)
- .agent/rules/**  (generated minimal governance rule(s))
- .agent/workflows/** (generated minimal workflows)
- .cursor/rules/repo-governance.mdc (generated Cursor rule)

By default, uses symlinks when possible; falls back to copying.
"""

from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]  # scripts/agents/ -> repo root


def _is_windows() -> bool:
    return os.name == "nt"


def _safe_unlink(path: Path) -> None:
    if not path.exists() and not path.is_symlink():
        return
    if path.is_symlink():
        path.unlink()
    elif path.is_file():
        path.unlink()
    elif path.is_dir():
        shutil.rmtree(path)


def _ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def _symlink_or_copy(src: Path, dst: Path, mode: str) -> str:
    """
    Mirror src to dst. If mode='auto', prefer symlink; if not possible, copy.
    Returns 'symlink' or 'copy'.
    """
    if dst.exists() or dst.is_symlink():
        _safe_unlink(dst)

    if mode == "copy":
        shutil.copytree(src, dst)
        return "copy"

    # symlink or auto
    try:
        # On Windows, symlink can require admin or dev mode; still try in auto mode.
        dst.symlink_to(src, target_is_directory=True)
        return "symlink"
    except Exception:
        if mode == "symlink":
            raise
        shutil.copytree(src, dst)
        return "copy"


def _write_text(path: Path, text: str) -> None:
    _ensure_dir(path.parent)
    path.write_text(text, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Sync tool shims from canonical agent governance sources.")
    ap.add_argument(
        "--mode",
        choices=["auto", "symlink", "copy"],
        default="auto",
        help="How to mirror skills into tool directories. Default: auto (symlink if possible).",
    )
    args = ap.parse_args()

    if _is_windows() and args.mode == "auto":
        args.mode = "copy"

    # Validate canonical sources exist
    agents_md = REPO_ROOT / "AGENTS.md"
    docs_dir = REPO_ROOT / "docs" / "agents"
    skills_src = REPO_ROOT / ".agents" / "skills"
    workflows_src = REPO_ROOT / ".agents" / "workflows"
    for p in [agents_md, docs_dir, skills_src, workflows_src]:
        if not p.exists():
            print(f"ERROR: missing canonical path: {p}", file=sys.stderr)
            return 2

    # 1) Mirror skills to tool-specific locations
    mirrors = [
        (skills_src, REPO_ROOT / ".claude" / "skills"),
        (skills_src, REPO_ROOT / ".gemini" / "skills"),
        (skills_src, REPO_ROOT / ".agent" / "skills"),
        (workflows_src, REPO_ROOT / ".agent" / "workflows"),
        (REPO_ROOT / "knowledge", REPO_ROOT / ".gemini" / "knowledge"),
    ]
    mirror_results = []
    for src, dst in mirrors:
        _ensure_dir(dst.parent)
        result = _symlink_or_copy(src, dst, args.mode)
        mirror_results.append((dst, result))

    # 2) Generate shim entrypoints and minimal Antigravity assets
    claude_md = REPO_ROOT / ".claude" / "CLAUDE.md"
    gemini_md = REPO_ROOT / ".gemini" / "GEMINI.md"
    ag_rule = REPO_ROOT / ".agent" / "rules" / "000-repo-governance.md"

    _write_text(
        claude_md,
        "\n".join(
            [
                "# CLAUDE.md (shim)",
                "",
                "> AUTO-GENERATED by `scripts/agents/sync_shims.py`.",
                "",
                "Canonical agent instructions live in `../AGENTS.md` and `../docs/agents/`.",
                "",
                "## Do this on every task",
                "- Read `AGENTS.md` first.",
                "- Follow the repo contract: edit canonical sources; regenerate shims; validate.",
                "",
                "## Pointers",
                "- Governance detail: `../docs/agents/GOVERNANCE.md`",
                "- Tooling notes: `../docs/agents/TOOLING.md`",
                "",
            ]
        )
        + "\n",
    )

    _ensure_dir(gemini_md.parent)
    # Gemini CLI supports @ imports; keep the shim tiny.
    _write_text(
        gemini_md,
        "\n".join(
            [
                "# GEMINI.md (shim)",
                "",
                "<!-- AUTO-GENERATED by `scripts/agents/sync_shims.py` -->",
                "",
                "@../AGENTS.md",
                "@../docs/agents/GOVERNANCE.md",
                "@../docs/agents/TOOLING.md",
                "@../docs/agents/KNOWLEDGE_SUBAGENT.md",
                "",
            ]
        )
        + "\n",
    )

    _write_text(
        ag_rule,
        "\n".join(
            [
                "---",
                "name: repo-governance",
                "description: Repo-wide governance rules for AI agents. Canonical source is AGENTS.md.",
                "---",
                "",
                "# Repo governance (Antigravity rule)",
                "",
                "> AUTO-GENERATED by `scripts/agents/sync_shims.py`.",
                "",
                "Follow the canonical instructions in `AGENTS.md`.",
                "",
                "## Non-negotiables",
                "- Edit canonical sources only (`AGENTS.md`, `docs/agents/**`, `.agents/skills/**`).",
                "- Regenerate shims after governance/skill changes: `python scripts/agents/sync_shims.py`.",
                "- Validate: `python ci/validate_agent_assets.py`.",
                "",
            ]
        )
        + "\n",
    )

    # 3) Generate Cursor rule
    gen_cursor = REPO_ROOT / "scripts" / "agents" / "generate_cursor_rule.py"
    if gen_cursor.exists():
        # Run in-process without importing external deps
        code = compile(gen_cursor.read_text(encoding="utf-8"), str(gen_cursor), "exec")
        ns = {"__name__": "__main__", "__file__": str(gen_cursor)}
        exec(code, ns, ns)

    # Output summary
    print("Synced shims.")
    for dst, how in mirror_results:
        print(f"- skills mirror: {dst} ({how})")
    print(f"- wrote: {claude_md}")
    print(f"- wrote: {gemini_md}")
    print(f"- wrote: {ag_rule}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
